/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCX_H_RPCGEN
#define	_RPCX_H_RPCGEN

#include <rpc/rpc.h>

typedef char *PadiString_t;

typedef u_int PadiSize_t;

typedef long PadiFunc_tp;

typedef int PadiStatus_t;

typedef char PadiBoolean_t;

typedef double PadiPrecision_t;

struct PadiResult_t {
	PadiFunc_tp xdr_proc;
	PadiStatus_t status;
};
typedef struct PadiResult_t PadiResult_t;

struct PadiListResult_t {
	PadiFunc_tp xdr_proc;
	PadiStatus_t status;
	struct {
		u_int list_len;
		PadiString_t *list_val;
	} list;
};
typedef struct PadiListResult_t PadiListResult_t;

struct PadiInfo_t {
	PadiString_t name;
	PadiString_t desc;
	PadiString_t class;
	PadiString_t type;
	PadiString_t access;
	PadiString_t frequency;
	PadiString_t start;
	PadiString_t end;
	PadiString_t format;
};
typedef struct PadiInfo_t PadiInfo_t;

struct PadiInfoResult_t {
	PadiFunc_tp xdr_proc;
	PadiStatus_t status;
	PadiInfo_t info;
};
typedef struct PadiInfoResult_t PadiInfoResult_t;

struct PadiRange_t {
	PadiString_t start;
	PadiString_t end;
	PadiSize_t nobs;
	PadiBoolean_t do_missing;
	PadiPrecision_t missing_translation[3];
	PadiString_t format;
};
typedef struct PadiRange_t PadiRange_t;

struct PadiRangeArg_t {
	PadiString_t object_name;
	PadiRange_t range;
};
typedef struct PadiRangeArg_t PadiRangeArg_t;

struct PadiSeries_t {
	PadiInfo_t info;
	PadiRange_t range;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct PadiSeries_t PadiSeries_t;

struct PadiSeriesResult_t {
	PadiFunc_tp xdr_proc;
	PadiStatus_t status;
	PadiSeries_t series;
};
typedef struct PadiSeriesResult_t PadiSeriesResult_t;

struct PadiNewSeries_t {
	PadiString_t dbname;
	PadiSeries_t series;
};
typedef struct PadiNewSeries_t PadiNewSeries_t;

#define	PADIPROG ((unsigned long)(0x20004444))
#define	PADIVERS ((unsigned long)(1))
#define	GETLIST ((unsigned long)(1))
extern  PadiListResult_t * getlist_1();
#define	GETINFO ((unsigned long)(2))
extern  PadiInfoResult_t * getinfo_1();
#define	GETSERIES ((unsigned long)(3))
extern  PadiSeriesResult_t * getseries_1();
#define	PUTSERIES ((unsigned long)(4))
extern  PadiResult_t * putseries_1();
#define	NEWSERIES ((unsigned long)(5))
extern  PadiResult_t * newseries_1();
#define	DESTROY ((unsigned long)(6))
extern  PadiResult_t * destroy_1();
extern int padiprog_1_freeresult();

/* the xdr functions */
extern bool_t xdr_PadiString_t();
extern bool_t xdr_PadiSize_t();
extern bool_t xdr_PadiFunc_tp();
extern bool_t xdr_PadiStatus_t();
extern bool_t xdr_PadiBoolean_t();
extern bool_t xdr_PadiPrecision_t();
extern bool_t xdr_PadiResult_t();
extern bool_t xdr_PadiListResult_t();
extern bool_t xdr_PadiInfo_t();
extern bool_t xdr_PadiInfoResult_t();
extern bool_t xdr_PadiRange_t();
extern bool_t xdr_PadiRangeArg_t();
extern bool_t xdr_PadiSeries_t();
extern bool_t xdr_PadiSeriesResult_t();
extern bool_t xdr_PadiNewSeries_t();

#endif /* !_RPCX_H_RPCGEN */
